<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="TCSDEN7JFYKP2" name="org.Testngconcepts.EmployeebothAssert" tests="4" failures="1" timestamp="08 Jul 2022 12:18:56 GMT" time="14.661" errors="0">
  <testcase name="tc3" time="7.772" classname="org.Testngconcepts.EmployeebothAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	verify the title expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
verify the title expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.Testngconcepts.EmployeebothAssert.tc3(EmployeebothAssert.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase name="tc4" time="6.889" classname="org.Testngconcepts.EmployeebothAssert"/>
  <testcase name="tc2" classname="org.Testngconcepts.EmployeebothAssert">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc1" classname="org.Testngconcepts.EmployeebothAssert">
    <skipped/>
  </testcase> <!-- tc1 -->
</testsuite> <!-- org.Testngconcepts.EmployeebothAssert -->
